### ISSUE TITLE
IGNORE - STEPHEN TEST

### ISSUE THREAD

**Issue by slemasne** [finbourne/lusid-sdk-csharp-preview#162]
## Bug Report Checklist

- [x] I have checked the existing [documentation](../../../../wiki) for this SDK
- [x] I have searched for any related issues/PRs
- [x] I have read the [LUISD contribution guidelines](../../docs/CONTRIBUTING.md)
- [x] I have read the [LUSID Code of Conduct](../../docs/CODE_OF_CONDUCT.md)

**SDK version**
The version of the SDK that has the bug. 

**IMPORTANT: DO NOT POST YOUR API CREDENTIALS OR ANY SENSITIVE DATA**

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**

**Comment by JeremyBarber** [comment]
The test is complete and the underlying issue has been resolved by SE-1396
